# Generated by Django 2.2 on 2020-12-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='contents',
            new_name='content',
        ),
    ]
